#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: librarian
#+AUTHOR: Andrew M Davis, PhD
#+EMAIL: @reconmaster:matrix.org
#+AUTHOR: Jonathan Zelaya
#+EMAIL: @ocelomeh:matrix.org
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.13)
#+FILETAGS: 気, ki, comp, library
Objective: Catalog knowledge

#+BEGIN_QUOTE
An original idea. That can’t be too hard. The library must be full of
them.

Fry 先生
#+END_QUOTE
* Introduction
Library sciences are an important study. Here we try to find an
optimal knowledge categorization methods for digital information using
open-source technologies.

* Tools of the Trade
Please see our [[file:docs/README.org][documentation]] folder for our current outline of tools
used to catalog our digital and physical libraries.

In addition to personal tools, examples of libraries both past and
present are given in the [[file:resources/README.org][resources]] section.

* Goal
In sharing these personal tools for managing collections of knowledge,
the global network of digital information can grow in a cataloged
manner such that future work can build on the existing body of
knowledge. We hope this helps contribute to an unrestricted digital
network of information that allows researchers equal access to the
same set of data.
